title : Graeme Harrison
description: ''

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
# baseurl: ''
url: "https://graemeharrison.com"
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
